# Generated by Django 4.2 on 2024-02-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("correo", models.EmailField(max_length=254)),
                (
                    "tipo_consulta",
                    models.IntegerField(
                        choices=[
                            [0, "consulta"],
                            [1, "reclamo"],
                            [2, "sugerencia"],
                            [3, "felicitaciones"],
                        ]
                    ),
                ),
                ("mensaje", models.TextField()),
            ],
        ),
    ]
