# Generated by Django 4.2 on 2024-02-13 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppMantenimientoHogar", "0002_producto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reparacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("producto", models.CharField(max_length=20)),
                ("problema", models.TextField()),
                ("estado", models.BooleanField(default=False)),
                (
                    "contacto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppMantenimientoHogar.contacto",
                    ),
                ),
            ],
        ),
    ]
